---
- hosts: bastion
  vars:
    sudouser: "{{ ansible_env['SUDO_USER'] }}"
  become: true

  tasks:
  - name: Get Spark Bundle From Internet
    get_url:
      url: http://archive.apache.org/dist/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
      dest: /tmp/spark-2.2.0-bin-hadoop2.7.tgz
      checksum: md5:17 15B661BDF33B40C98B3DAA7837F690

- hosts: spark
  vars:
    sudouser: "{{ ansible_env['SUDO_USER'] }}"
  become: true

  tasks:
  - name: Install Java
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: Copy Spark Bundle to Spark Nodes
    copy:
      src: /tmp/spark-2.2.0-bin-hadoop2.7.tgz
      dest: /tmp/spark-2.2.0-bin-hadoop2.7.tgz
      
  - name: Create Spark User
    user:
      name: spark
      system: yes

  - name: Create Spark Folder /opt/spark
    file:
      path: /opt/spark
      state: directory

  - name: Unarchive Spark Bundle
    unarchive:
      src: /tmp/spark-2.2.0-bin-hadoop2.7.tgz
      dest: /opt/spark
      extra_opts: [--strip-components=1]

  - name: Copy log4j.properties to config
    copy:
      src: ../files/log4j.properties
      dest: /opt/spark/conf/log4j.properties

  - name: Change Owner/Perms /opt/spark
    file:
      path: /opt/spark
      state: directory
      owner: spark
      group: spark
      mode: 0775
      recurse: yes      
